AmplayerAPI: player_ctrl.c File Reference
player_ctrl.c File Reference
#include <pthread.h>
#include <player.h>
#include <player_set_sys.h>
#include "player_ts.h"
#include "player_es.h"
#include "player_rm.h"
#include "player_ps.h"
#include "player_video.h"
#include "player_audio.h"
#include "player_update.h"
#include "thread_mgt.h"
#include "player_ffmpeg_ctrl.h"
#include "player_cache_mgt.h"
Defines
#define FBIOPUT_OSD_SRCCOLORKEY 0x46fb
#define FBIOPUT_OSD_SRCKEY_ENABLE 0x46fa
Functions
void print_version_info ()
player_init
int player_init (void)
int player_start (play_control_t *ctrl_p, unsigned long priv)
player_start
int player_start_play (int pid)
player_start_play
int player_stop (int pid)
player_stop
int player_stop_async (int pid)
player_stop
int player_exit (int pid)
player_exit
int player_pause (int pid)
player_pause
int player_resume (int pid)
player_resume
int player_loop (int pid)
player_loop
int player_noloop (int pid)
player_loop
int player_timesearch (int pid, int s_time)
player_timesearch
int player_forward (int pid, int speed)
player_forward
int player_backward (int pid, int speed)
player_backward
int player_aid (int pid, int audio_id)
player_aid
int player_sid (int pid, int sub_id)
player_sid
int player_enable_autobuffer (int pid, int enable)
player_enable_autobuffer
int player_set_autobuffer_level (int pid, float min, float middle, float max)
player_set_autobuffer_level
int player_send_message (int pid, player_cmd_t *cmd)
player_send_message
int player_register_update_callback (callback_t *cb, update_state_fun_t up_fn, int interval_s)
player_register_update_callback
player_status player_get_state (int pid)
player_get_state
unsigned int player_get_extern_priv (int pid)
player_get_extern_priv
int player_get_play_info (int pid, player_info_t *info)
player_get_play_info
int player_get_media_info (int pid, media_info_t *minfo)
player_get_media_info
int player_video_overlay_en (unsigned enable)
player_video_overlay_en
int audio_set_mute (int pid, int mute_on)
audio_set_mute
int audio_get_volume_range (int pid, int *min, int *max)
audio_get_volume_range
int audio_set_volume (int pid, float val)
audio_set_volume
int audio_get_volume (int pid, float *vol)
audio_get_volume
int audio_set_volume_balance (int pid, int balance)
audio_set_volume_balance
int audio_swap_left_right (int pid)
audio_swap_left_right
int audio_left_mono (int pid)
audio_left_mono
int audio_right_mono (int pid)
audio_right_mono
int audio_stereo (int pid)
audio_stereo
int audio_set_spectrum_switch (int pid, int isStart, int interval)
audio_set_spectrum_switch
int player_progress_exit (void)
player_progress_exit
int player_list_allpid (pid_info_t *pid)
player_list_allpid
int player_cache_system_init (int enable, const char *dir, int max_size, int block_size)
player_cache_system_init
char * player_status2str (player_status status)
player_status2str
Detailed Description
Author:
Xu Hui <hui.xu@amlogic.com>
Version:
1.0.0
Date:
2011-02-21
Definition in file player_ctrl.c.
Function Documentation
int audio_get_volume (int pid, float * vol)
audio_get_volume
Parameters:
[in] pid player tag which get from player_start return value
Returns:
r current volume
get volume
Definition at line 1003 of file player_ctrl.c.
int audio_get_volume_range (int pid, int * min, int * max)
audio_get_volume_range
Parameters:
[in] pid player tag which get from player_start return value
[out] min volume minimum
[out] max volume maximum
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
get volume range
Definition at line 969 of file player_ctrl.c.
int audio_left_mono (int pid)
audio_left_mono
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
Definition at line 1059 of file player_ctrl.c.
int audio_right_mono (int pid)
audio_right_mono
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
Definition at line 1089 of file player_ctrl.c.
int audio_set_mute (int pid, int mute_on)
audio_set_mute
Parameters:
[in] pid player tag which get from player_start return value
[in] mute_on volume mute flag 1:mute 0:inmute
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
volume mute switch
Definition at line 931 of file player_ctrl.c.
int audio_set_spectrum_switch (int pid, int isStart, int interval)
audio_set_spectrum_switch
Parameters:
[in] pid player tag which get from player_start return value
[in] isStart open/close spectrum switch function
[in] interval swtich interval
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
Definition at line 1151 of file player_ctrl.c.
int audio_set_volume (int pid, float val)
audio_set_volume
Parameters:
[in] pid player tag which get from player_start return value
[in] val volume value
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
set volume to val
Definition at line 987 of file player_ctrl.c.
int audio_set_volume_balance (int pid, int balance)
audio_set_volume_balance
Parameters:
[in] pid player tag which get from player_start return value
[in] balance balance flag 1:set balance 0:cancel balance
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
balance switch
Definition at line 1026 of file player_ctrl.c.
int audio_stereo (int pid)
audio_stereo
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
Definition at line 1119 of file player_ctrl.c.
int audio_swap_left_right (int pid)
audio_swap_left_right
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
swap left and right channel
Definition at line 1043 of file player_ctrl.c.
int player_aid (int pid, int audio_id)
player_aid
Parameters:
[in] pid player tag which get from player_start return value
[in] audio_id target audio stream id, can find through media_info command
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send switch audio id command to player.
Definition at line 558 of file player_ctrl.c.
int player_backward (int pid, int speed)
player_backward
Parameters:
[in] pid player tag which get from player_start return value
[in] speed fast backward step
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send fb command to player. After fb, player playback from a key frame
Definition at line 525 of file player_ctrl.c.
int player_cache_system_init (int enable, const char * dir, int max_size, int block_size)
player_cache_system_init
Parameters:
[in] enable dir max_size block_size
Returns:
0;
Definition at line 1228 of file player_ctrl.c.
int player_enable_autobuffer (int pid, int enable)
player_enable_autobuffer
Parameters:
[in] pid player tag which get from player_start return value
[in] enable enable/disable auto buffer function
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
enable/disable auto buffering
Definition at line 625 of file player_ctrl.c.
int player_exit (int pid)
player_exit
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
player_exit must with pairs of player_play
Definition at line 296 of file player_ctrl.c.
int player_forward (int pid, int speed)
player_forward
Parameters:
[in] pid player tag which get from player_start return value
[in] speed fast forward step
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send ff command to player. After ff, player playback from a key frame
Definition at line 492 of file player_ctrl.c.
unsigned int player_get_extern_priv (int pid)
player_get_extern_priv
Parameters:
[in] pid player tag which get from player_start return value
Returns:
externed player's unique identification PLAYER_NOT_VALID_PID error,invalid pid
get current player's unique identification
Definition at line 800 of file player_ctrl.c.
int player_get_media_info (int pid, media_info_t * minfo)
player_get_media_info
Parameters:
[in] pid player tag which get from player_start return value
[out] minfo media info structure pointer
Returns:
PLAYER_SUCCESS success PLAYER_NOT_VALID_PID error,invalid pid
get file media information
Definition at line 859 of file player_ctrl.c.
int player_get_play_info (int pid, player_info_t * info)
player_get_play_info
Parameters:
[in] pid player tag which get from player_start return value
[out] info play info structure pointer
Returns:
PLAYER_SUCCESS success PLAYER_NOT_VALID_PID error,invalid pid
get player's information
Definition at line 830 of file player_ctrl.c.
player_status player_get_state (int pid)
player_get_state
Parameters:
[in] pid player tag which get from player_start return value
Returns:
status player current status PLAYER_NOT_VALID_PID error,invalid pid
get player current status
Definition at line 772 of file player_ctrl.c.
Referenced by player_send_message().
int player_list_allpid (pid_info_t * pid)
player_list_allpid
Parameters:
[out] pid pid list structure pointer
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
list all alived player pid
Definition at line 1201 of file player_ctrl.c.
int player_loop (int pid)
player_loop
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send loop command to set loop play current file
Definition at line 396 of file player_ctrl.c.
int player_noloop (int pid)
player_loop
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send noloop command to cancle loop play
Definition at line 427 of file player_ctrl.c.
int player_pause (int pid)
player_pause
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send pause command to player
Definition at line 336 of file player_ctrl.c.
int player_progress_exit (void)
player_progress_exit
Returns:
PLAYER_SUCCESS success
used for all exit,please only call at this process fatal error. Do not wait any things in this function
Definition at line 1181 of file player_ctrl.c.
int player_register_update_callback (callback_t * cb, update_state_fun_t up_fn, int interval_s)
player_register_update_callback
Parameters:
[in] cb callback structure point
[in] up_fn update function
[in] interval_s update interval
Returns:
PLAYER_EMPTY_P invalid pointer PLAYER_ERROR_CALLBACK up_fn invalid PLAYER_SUCCESS success
App register a callback function in player to notify message
Definition at line 747 of file player_ctrl.c.
int player_resume (int pid)
player_resume
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send resume command to player
Definition at line 366 of file player_ctrl.c.
int player_send_message (int pid, player_cmd_t * cmd)
player_send_message
Parameters:
[in] pid player tag which get from player_start return value
[in] cmd player control command
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send player control message
Definition at line 701 of file player_ctrl.c.
Referenced by player_aid(), player_backward(), player_enable_autobuffer(), player_forward(), player_loop(), player_noloop(), player_pause(), player_resume(), player_set_autobuffer_level(), player_sid(), and player_timesearch().
int player_set_autobuffer_level (int pid, float min, float middle, float max)
player_set_autobuffer_level
Parameters:
[in] pid player tag which get from player_start return value
[in] min buffer min percent (less than min, enter buffering, av pause)
[in] middle buffer middle percent(more than middler, exit buffering, av resume)
[in] max buffer max percent(more than max, do not feed data)
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
enable/disable auto buffering
Definition at line 660 of file player_ctrl.c.
int player_sid (int pid, int sub_id)
player_sid
Parameters:
[in] pid player tag which get from player_start return value
[in] sub_id target subtitle stream id, can find through media_info command
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send switch subtitle id command to player.
Definition at line 592 of file player_ctrl.c.
int player_start (play_control_t * ctrl_p, unsigned long priv)
player_start
Parameters:
[in] ctrl_p player control parameters structure pointer
[in] priv Player unique identification
Returns:
pid current player tag
Amlogic player start to play a specified path streaming file. If need_start in ctrl_p is setting 1, it need call player_start_play to playback, else playback immediately
Definition at line 90 of file player_ctrl.c.
int player_start_play (int pid)
player_start_play
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
if need_start set 1, need call player_start_play to start playback
Definition at line 157 of file player_ctrl.c.
char* player_status2str (player_status status)
player_status2str
Parameters:
[in] status player status
Returns:
player status details strings
Definition at line 1242 of file player_ctrl.c.
int player_stop (int pid)
player_stop
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send stop command to player (synchronous)
Definition at line 197 of file player_ctrl.c.
Referenced by player_exit().
int player_stop_async (int pid)
player_stop
Parameters:
[in] pid player tag which get from player_start return value
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
send stop command to player (asynchronous)
av_ioctrl(player_para->pFormatCtx, AVIOCTL_STOP, 0, 0);
Definition at line 251 of file player_ctrl.c.
int player_timesearch (int pid, int s_time)
player_timesearch
Parameters:
[in] pid player tag which get from player_start return value
[in] s_time target time, unit is second
Returns:
PLAYER_NOT_VALID_PID playet tag invalid PLAYER_NOMEM alloc memory failed PLAYER_SUCCESS success
seek to designated time point to play. After time search, player playback from a key frame
Definition at line 459 of file player_ctrl.c.
int player_video_overlay_en (unsigned enable)
player_video_overlay_en
Parameters:
[in] enable osd colorkey enable flag
Returns:
PLAYER_SUCCESS success PLAYER_FAILED failed
enable osd colorkey
Definition at line 895 of file player_ctrl.c.
void print_version_info ()
player_init
Returns:
PLAYER_SUCCESS success
Amlogic player initilization. Make sure call it once when setup amlogic player every time